# Generated by Django 5.0.8 on 2024-08-08 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('lat_decimal', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lon_decimal', models.DecimalField(decimal_places=15, max_digits=20)),
                ('building_type', models.CharField(choices=[('azs', 'АЗС'), ('nb', 'Нефтяная база'), ('shop', 'Магазин'), ('stock', 'Склад'), ('office', 'Офис')], max_length=50, verbose_name='Тип объекта')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
