# Generated by Django 5.0.8 on 2024-08-09 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterField(
            model_name='building',
            name='lat_decimal',
            field=models.DecimalField(decimal_places=15, max_digits=20, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='building',
            name='lon_decimal',
            field=models.DecimalField(decimal_places=15, max_digits=20, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='building',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_as_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
    ]
