# Generated by Django 5.0.8 on 2024-08-09 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_alter_building_options_alter_building_lat_decimal_and_more'),
        ('department', '0007_alter_department_manager'),
        ('user', '0002_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_list', to='building.building', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_list', to='department.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('specialist', 'Специалист'), ('senior_specialist', 'Старший специалист'), ('deputy_head', 'Заместитель руководителя'), ('supervisor', 'Руководитель')], max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
