# Generated by Django 5.0.8 on 2024-08-08 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_description_alter_department_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='Наследуется от'),
        ),
    ]
