# Generated by Django 5.0.8 on 2024-08-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_alter_department_manager'),
        ('department', '0009_alter_department_parent'),
    ]

    operations = [
    ]
